version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: 'Properties\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: ProcessCpuUsageStatusWindow.sln
  verbosity: minimal
after_build:
- ps: >-
    nuget pack ProcessCpuUsageStatusWindow.nuspec -Version $env:APPVEYOR_BUILD_VERSION -Properties Configuration=Release -OutputDirectory bin\Release\

    $squirrel = ".\packages\squirrel.windows.*\tools\Squirrel.exe"

    .$squirrel -releasify ".\bin\$env:CONFIGURATION\ProcessCpuUsageStatusWindow.$version.nupkg"
artifacts:
- path: bin\$(configuration)\ProcessCpuUsageStatusWindow.*.nupkg
  name: Package
- path: Release\**\*
  name: Release
deploy:
- provider: Environment
  name: GitHub
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore