//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessCpuUsageStatusWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProcessCpuUsageStatusWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddItemLink {
            get {
                return ResourceManager.GetString("AddItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItemToolTip {
            get {
                return ResourceManager.GetString("AddItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process CPU Usage Status Window.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update....
        /// </summary>
        public static string CheckingForUpdate {
            get {
                return ResourceManager.GetString("CheckingForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check for Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Now.
        /// </summary>
        public static string checkVersionNowButton {
            get {
                return ResourceManager.GetString("checkVersionNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Check for a new version on startup.
        /// </summary>
        public static string checkVersionOnStartupCheckBox {
            get {
                return ResourceManager.GetString("checkVersionOnStartupCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected items?.
        /// </summary>
        public static string ConfirmDeleteItemss {
            get {
                return ResourceManager.GetString("ConfirmDeleteItemss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteItemLink {
            get {
                return ResourceManager.GetString("DeleteItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string DeleteItemToolTip {
            get {
                return ResourceManager.GetString("DeleteItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditItemLink {
            get {
                return ResourceManager.GetString("EditItemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string EditItemToolTip {
            get {
                return ResourceManager.GetString("EditItemToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: {0,4:f1}% - Total.
        /// </summary>
        public static string FooterLine {
            get {
                return ResourceManager.GetString("FooterLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing update....
        /// </summary>
        public static string InstallingUpdate {
            get {
                return ResourceManager.GetString("InstallingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ItemColumnHeader {
            get {
                return ResourceManager.GetString("ItemColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string ItemWindowAdd {
            get {
                return ResourceManager.GetString("ItemWindowAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Item.
        /// </summary>
        public static string ItemWindowEdit {
            get {
                return ResourceManager.GetString("ItemWindowEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Number of processes:.
        /// </summary>
        public static string NumberOfProcesses {
            get {
                return ResourceManager.GetString("NumberOfProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkayButton {
            get {
                return ResourceManager.GetString("OkayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string optionCategoryAbout {
            get {
                return ResourceManager.GetString("optionCategoryAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string optionCategoryGeneral {
            get {
                return ResourceManager.GetString("optionCategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string optionCategoryItems {
            get {
                return ResourceManager.GetString("optionCategoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string optionCategoryUpdate {
            get {
                return ResourceManager.GetString("optionCategoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: {1,4:f1}% - {0}.
        /// </summary>
        public static string ProcessLine {
            get {
                return ResourceManager.GetString("ProcessLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU: {1,4:f1}% - {0} ({2}).
        /// </summary>
        public static string ProcessLineWithProcessId {
            get {
                return ResourceManager.GetString("ProcessLineWithProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _process ID.
        /// </summary>
        public static string showProcessId {
            get {
                return ResourceManager.GetString("showProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start when Windows starts.
        /// </summary>
        public static string startWithWindowsCheckBox {
            get {
                return ResourceManager.GetString("startWithWindowsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already running the most recent version.
        ///
        ///No updates are available at this time..
        /// </summary>
        public static string UpdateCheckCurrent {
            get {
                return ResourceManager.GetString("UpdateCheckCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is now available.
        ///
        ///Would you like to download and install it now?.
        /// </summary>
        public static string UpdateCheckNewVersion {
            get {
                return ResourceManager.GetString("UpdateCheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Update.
        /// </summary>
        public static string UpdateCheckTitle {
            get {
                return ResourceManager.GetString("UpdateCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
